Update master/ to 3.2 before updating before work.
Master has been neglected for work in branches.  Will update master to
latest 3.2 branch before working on updating to latest GNOME.

diff --git a/build/buildgsb b/build/buildgsb
--- a/build/buildgsb
+++ b/build/buildgsb
@@ -25,8 +25,7 @@
 # IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY
 # OF SUCH DAMAGE.
 
-# GNOME SlackBuild Version
-GSB_VERSION=2_32
+GSB_VERSION=3.2
 
 #========================================================================
 # FUNCTIONS
@@ -41,10 +40,24 @@ trap error_out SIGINT
 #========================================================================
 # ENVIRONMENT
 
+ARCH=${ARCH:-$(uname -m)}
 # If the user created an options file, read it.
-[ -r ./gsb.options ] && {
-  . ./gsb.options
-  export OPTIONSREAD=1
+if [ -r ./gsb.options.${ARCH} ]; then
+  . ./gsb.options.${ARCH} ;
+  export OPTIONSREAD=1 ;
+else
+  echo "Warning: no defined gsb.options.${ARCH}" && exit 1
+fi;
+
+#========================================================================
+# VERSIONS
+
+# If the user created an options file, read it.
+GSB_SOURCE_VERSION="3.0"
+GNOME_VERSION="3.0.1"
+SLACKWARE_VERSION="13.37"
+[ -r ../VERSIONS ] && {
+  . ../VERSIONS
 }
 
 # Basic settings
@@ -79,11 +92,13 @@ PATCHESDIR=${PATCHESDIR:-patches}
 
 # Option defaults.
 WITH_TEST_PACKAGES=0
+WITH_PASTURE_PACKAGES=0
 AUTO_DOWNLOAD=0
 ONLY_DOWNLOAD=0
 CONFIRM_INSTALLS=0
 NOPATCHESDIR=0
 NOSKIP=0
+CLEANUP=0
 SKIP_REBUILDS=0
 NOPRUNE=0
 PUBLISH=0
@@ -97,12 +112,8 @@ WGET_OPTIONS="-4"
 #
 while [ -n "$1" ] ; do
   case $1 in
-    -force|--force)
-      SLACKBUILD_ARGS="${SLACKBUILD_ARGS:+"$SLACKBUILD_ARGS "}--force"
-      shift
-    ;;
-    -no-cleanup|--no-cleanup)
-      SLACKBUILD_ARGS="${SLACKBUILD_ARGS:+"$SLACKBUILD_ARGS "}--no-cleanup"
+    -cleanup|--cleanup)
+      CLEANUP=1
       shift
     ;;
     -no-patchesdir|--no-patchesdir)
@@ -125,6 +136,10 @@ while [ -n "$1" ] ; do
     ;;
     -with-testing|--with-testing)
       WITH_TEST_PACKAGES=1
+      shift
+    ;;
+    -with-pasture|--with-pasture)
+      WITH_PASTURE_PACKAGES=1
       shift
     ;;
     -confirm-installs|--confirm-installs)
@@ -199,6 +214,8 @@ BUILDLIST=${BUILDLIST:-""}
 BUILDLIST="$(egrep -v "^#|^$" buildlist.txt | \
   # Remove our testing packages if not specified.
   if [ "$WITH_TEST_PACKAGES" = "1" ]; then cat ; else egrep -v testing; fi | \
+  # Remove our pasture packages if not specified.
+  if [ "$WITH_PASTURE_PACKAGES" = "1" ]; then cat ; else egrep -v pasture; fi | \
   # Perhaps the user only wants a certain set of packages.
   if [ -z "$SETS" ]; then cat ; else egrep ^${SETS}; fi | \
   # Perhaps the user only wants a specific package. 
@@ -211,14 +228,24 @@ BUILDLIST="$(egrep -v "^#|^$" buildlist.txt | \
 }
 
 #========================================================================
-# CLEAN SYSTEM OF TESTING/ PACKAGES
+# CLEAN SYSTEM OF TESTING/ AND PASTURE/ PACKAGES
 #
-# Clear the system of any packages from testing/ which might be lying around.
-# This ensures that we don't accidently build against a package we don't want.
+# Clear the system of any packages from testing/ or pasture/ which might be
+# lying around.  This ensures that we don't accidently build against a package
+# we don't want.
 #
 if [ "$WITH_TEST_PACKAGES" = "0" -a "${ONLY_DOWNLOAD}" = "0" ]; then
-  echo; header "Removing any test packages."
+  echo; header "Removing any testing/ packages."
 ( cd ${BUILDSOURCE}/../testing &&
+  for testpkg in $(find . -type d -mindepth 1 -maxdepth 1); do
+    removepkg $testpkg 1>/dev/null 2>/dev/null
+  done;
+)
+fi;
+
+if [ "$WITH_PASTURE_PACKAGES" = "0" -a "${ONLY_DOWNLOAD}" = "0" ]; then
+  echo; header "Removing any pasture/ packages."
+( cd ${BUILDSOURCE}/../pasture &&
   for testpkg in $(find . -type d -mindepth 1 -maxdepth 1); do
     removepkg $testpkg 1>/dev/null 2>/dev/null
   done;
@@ -368,6 +395,24 @@ elif [ "$SKIP_BUILD" = "0" -o "$BUILD_OPTION" = "rebuild" -a "$SKIP_REBUILDS" = 
      exit $ERR 
    }
    SUCCESSFUL_NEW_BUILD=1
+
+   [ "$CLEANUP" = "1" ] && {
+     echo "Cleaning up ${PACKAGE}."
+     rm -fr $TMP/${PACKAGE}-*
+     rm -fr $TMP/package-${PACKAGE}-*
+   }
+
+
+  CHK_PACKAGE="$( find_package_files "$PKGDEST/$SUBDIR" "${PACKAGE//+/\+}" \
+	      "${PACKAGE_VERSION//-/_}" "" "${PACKAGE_BUILD}${TAG}" "\.txz" )"
+
+  make_pkg_txt "$CHK_PACKAGE" || {
+      header "Failed to create txt description for '$PACKAGE'." ; exit 1
+  }
+  make_pkg_asc "$CHK_PACKAGE" || {
+      header "Failed to create asc signature for '$PACKAGE'." ; exit 1
+  }
+
 else
   echo "* Found: $PACKAGE-${PACKAGE_VERSION//-/_}-${ARCH}-${PACKAGE_BUILD}${TAG}.txz" 
 fi
@@ -381,7 +426,7 @@ if [ "${NOPRUNE}" = "0" -a "${ONLY_DOWNLOAD}" = "0" ]; then
   PRUNE_FILES="$( find_package_files "$PKGDEST/$SUBDIR" "${PACKAGE//+/\+}" \
     "" "" "" "\.txz|\.txt|\.txz\.asc" | grep -v "$( find_package_files \
     "$PKGDEST/$SUBDIR" "${PACKAGE//+/\+}" "${PACKAGE_VERSION//-/_}" "" \
-    "${PACKAGE_BUILD}${TAG}" "\.txz|\.txz\.asc" )" | tr '\n' ' ' )"
+    "${PACKAGE_BUILD}${TAG}" "\.txt|\.txz|\.txz\.asc" )" | tr '\n' ' ' )"
   [ ! -z "$PRUNE_FILES" ] && {
       rm -f $PRUNE_FILES
   }
@@ -392,23 +437,22 @@ fi;
 #
 # Make a txt description of the package
 if [ "$PUBLISH" = "1" -a "${ONLY_DOWNLOAD}" = "0" ]; then
-  make_pkg_txt "$( find_package_files "$PKGDEST/$SUBDIR" "${PACKAGE//+/\+}" \
-    "${PACKAGE_VERSION//-/_}" "" "${PACKAGE_BUILD}${TAG}" "\.txz" )" || {
-    header "Failed to create txt description for '$PACKAGE'." ; exit 1
-  }
   # Sign the package
-  SIGN_PACKAGE="$( find_package_files "$PKGDEST/$SUBDIR" "${PACKAGE//+/\+}" \
+  CHK_PACKAGE="$( find_package_files "$PKGDEST/$SUBDIR" "${PACKAGE//+/\+}" \
     "${PACKAGE_VERSION//-/_}" "" "${PACKAGE_BUILD}${TAG}" "\.txz" )"
-  if [ -f ${SIGN_PACKAGE}.asc ]; then
-    gpg --verify ${SIGN_PACKAGE}.asc ${SIGN_PACKAGE} 1>/dev/null 2>/dev/null || {
-      echo ;echo ; header "$SIGN_PACKAGE failed to pass asc verification."
+  if [ ! -f ${CHK_PACKAGE//txz/txt} ]; then
+	  echo "No .txt found for $CHK_PACKAGE." && exit 1 ;
+  fi;
+  if [ -f ${CHK_PACKAGE}.asc ]; then
+    gpg --verify ${CHK_PACKAGE}.asc ${CHK_PACKAGE} 1>/dev/null 2>/dev/null || {
+      echo ;echo ; header "$CHK_PACKAGE failed to pass asc verification."
       echo "Has the package been corrupted?" ;
       exit 1
     }
     echo " (ASC Signature passed.) "
   else
     echo ; echogreen "* " ; echo "Please sign for ${PACKAGE}:"
-    make_pkg_asc "$SIGN_PACKAGE" || {
+    make_pkg_asc "$CHK_PACKAGE" || {
       header "Failed to create asc signature for '$PACKAGE'." ; exit 1
     }
   fi;
@@ -457,28 +501,46 @@ done
 #
 if [ "${PUBLISH}" = "1" -a "${ONLY_DOWNLOAD}" = "0" ]; then
 (
-cd $BUILDSOURCE ;
+#cd $BUILDSOURCE ;
 # Copy tagfiles
-for tagfile in $(find . -type f -name tagfile); 
-do 
- cp $tagfile $PKGDEST/$GSBDIR/$(echo $tagfile | cut -f2 -d/) || exit 1
-done;
+#for tagfile in $(find . -type f -name tagfile); 
+#do 
+ #mkdir -p $PKGDEST/$GSBDIR/$(echo $tagfile | cut -f2 -d/) &&
+ #if [ ! -f $PKGDEST/$GSBDIR/$(echo $tagfile | cut -f2 -d/)/tagfile ];  then
+  #cp $tagfile $PKGDEST/$GSBDIR/$(echo $tagfile | cut -f2 -d/) || exit 1
+ #else
+ #if [ "$(cat ${tagfile} | md5sum )" != "$(cat $PKGDEST/$GSBDIR/$(echo $tagfile | cut -f2 -d/)/tagfile | md5sum)" ];
+ #then 
+  #cp $tagfile $PKGDEST/$GSBDIR/$(echo $tagfile | cut -f2 -d/) || exit 1
+ #fi;
+ #fi;
+#done;
 
 # Copy our main documentation
 cd $BUILDSOURCE/.. ;
 if [ "$ARCH" = "x86_64" ]; then
-  cat README.TXT | sed 's,@BINARY_EDITION@,64-bit x86_64 edition,g' > \
+  cat README.TXT | sed 's,@BINARY_EDITION@,64-bit x86_64 edition,g' \
+  | sed "s,@GNOME_VERSION@,${GNOME_VERSION},g" > \
     $PKGDEST/README.TXT ;
 else
-  cat README.TXT | sed 's,@BINARY_EDITION@,32-bit x86 edition,g' > \
+  cat README.TXT | sed 's,@BINARY_EDITION@,32-bit x86 edition,g' \
+  | sed "s,@GNOME_VERSION@,${GNOME_VERSION},g" > \
     $PKGDEST/README.TXT ;
 fi;
+
+cat SLACKWARE_REPLACED_PACKAGES.TXT | sed "s,@GNOME_VERSION@,${GNOME_VERSION},g" > \
+	$PKGDEST/SLACKWARE_REPLACED_PACKAGES.TXT || exit 1
+
 for i in COPYING COPYING3 CREDITS INSTALL.TXT UPGRADE.TXT \
  CHANGES_AND_HINTS.TXT GPG-KEY COPYRIGHT.TXT MIRRORS.TXT CURRENT.WARNING \
- SLACKWARE_REPLACED_PACKAGES.TXT FAQ.TXT ANNOUNCE.$GSB_VERSION;
+ FAQ.TXT ANNOUNCE.${GSB_VERSION}
 do
  if [ -f $i ]; then
-   cp $i $PKGDEST || exit 1;
+   # Only copy over if changed in order to preserve timestamp
+   if [ "$(cat ${i} | md5sum )" != "$(cat $PKGDEST/${i} | md5sum )" ];
+     then 
+       cp -p $i $PKGDEST/${i} || exit 1;
+   fi;
  fi;
 done;
 
@@ -493,17 +555,16 @@ Have fun!
 EOF
 
 # Copy extra documentation
-cp extra/README.TXT $PKGDEST/$EXTRADIR || exit 1
-[ "$WITH_TEST_PACKAGES" = "1" ] && {
-  cp testing/README.TXT $PKGDEST/$TESTINGDIR || exit 1
-}
+cp -p extra/README.TXT $PKGDEST/$EXTRADIR || exit 1
+#[ "$WITH_TEST_PACKAGES" = "1" ] && {
+  #cp -p testing/README.TXT $PKGDEST/$TESTINGDIR || exit 1
+#}
 if [ "$ARCH" = "x86_64" ]; then
-  cp ChangeLog.slackware64 $PKGDEST/ChangeLog.txt &&
-  cp VERSIONS.slackware64 $PKGDEST/VERSIONS || exit 1
+  cp -p ChangeLog.slackware64 $PKGDEST/ChangeLog.txt 
 else
-  cp ChangeLog.slackware $PKGDEST/ChangeLog.txt &&
-  cp VERSIONS.slackware $PKGDEST/VERSIONS || exit 1
+  cp -p ChangeLog.slackware $PKGDEST/ChangeLog.txt 
 fi
+cp -p VERSIONS $PKGDEST/VERSIONS 
 echo;
 header "* Published documentation."
 echo;
